apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cicd-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-cicd-kube
  template:
    metadata:
      labels:
        app: node-cicd-kube
    spec:
      containers:
      - name: node-cicd-kube
        image: herve97/node-cicd-kube:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
