apiVersion: v1
kind: Service
metadata:
  name: node-cicd-kube-service
spec:
  selector:
    app: node-cicd-kube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
  # type: LoadBalancer
