name: Build, Push & Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/node-cicd-kube

jobs:
  deploy-to-local:
    runs-on: self-hosted # Runner auto-hébergé sur votre machine
    steps:
      - name: Kill locking processes
        shell: powershell
        run: |
         Stop-Process -Name "node" -Force -ErrorAction SilentlyContinue
         Stop-Process -Name "git" -Force -ErrorAction SilentlyContinue
         Start-Sleep -Seconds 2
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            clean: false
            fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA .
          docker push $IMAGE_NAME:$GITHUB_SHA

      - name: Deploy to Local Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment/node-app

      - name: Clean workspace
        run: |
            git clean -ffdx
            git reset --hard HEAD