name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/node-cicd-kube

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      run: |
        docker build -t $IMAGE_NAME:$GITHUB_SHA .
        docker push $IMAGE_NAME:$GITHUB_SHA

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: k8s/deployment.yaml
        images: |
          $IMAGE_NAME:$GITHUB_SHA
        kubectl-version: "1.22.0"