name: Build, Push & Deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/node-cicd-kube

jobs:
  deploy-to-local:
    runs-on: self-hosted # Runner auto-hébergé sur votre machine
    steps:
      - name: Kill processes with Handle
        shell: powershell
        run: |
          # Vérifier l'installation
          if (-not (Test-Path "C:\Sysinternals\handle64.exe")) {
              throw "Handle64 non installé"
          }
          
          # Appel avec chemin absolu
          & "C:\Sysinternals\handle64.exe" -accepteula -nobanner "$env:GITHUB_WORKSPACE" | ForEach-Object {
              if ($_ -match 'pid:(\d+)') {
                  Stop-Process -Id $matches[1] -Force -ErrorAction SilentlyContinue
              }
          }
     
      - name: Préparation Workspace
        shell: cmd
        run: |
          powercfg -h off >nul 2>&1
          icacls "C:\actions-runner\*" /grant "*S-1-1-0:(OI)(CI)F" /C >nul
          fsutil behavior set disablelastaccess 1 >nul
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            clean: false
            fetch-depth: 0
            sparse-checkout: |
             /*
             !node_modules/
            persist-credentials: false

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA .
          docker push $IMAGE_NAME:$GITHUB_SHA

      - name: Deploy to Local Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment/node-app

      - name: Clean workspace
        run: |
            git clean -ffdx
            git reset --hard HEAD